
language: python

python:
  - { PATH: "{{Python39}}", VERSION: 3.9, DIST: std, PYINT: python3.9, PYTHONPATH: src }
  
virtualenv:
  - path: {{ospathjoin(root_path, pickname("$NAME_JENKINS", project_name + "_$VERSION_$DIST_$NAME"), "_venv")}}
  
install:
  - $PYINT -m pip install --upgrade pip
  - $PYINT -m pip install --upgrade --no-cache-dir --no-deps --index http://localhost:8067/simple/ jyquickhelper pyquickhelper pymyinstall pyensae scikit-learn --extra-index-url=https://pypi.python.org/simple/
  - $PYINT -m pip install -r requirements.txt
  - $PYINT --version
  - $PYINT -m pip freeze

before_script:
  - python -u setup.py build_ext --inplace
  - set KERAS_BACKEND=tensorflow

script:
  - { CMD: "$PYINT -u setup.py unittests -g \".*((MODULE)|(210)|(300)|(400)|(code_style)|(test_torch)).*\"", NAME: "UT", TIMEOUT: 3600, SCHEDULER: "H H(1-2) 25 * *" }
  - { CMD: "$PYINT -u setup.py unittests -e \".*(code_style).*\"", NAME: "UT_STYLE", TIMEOUT: 4800, SCHEDULER: "H H(1-2) 25 * *" }
  - { CMD: "$PYINT -u setup.py unittests -e \".*((keras)).*\"", NAME: "UT_KERAS", TIMEOUT: 12000, SCHEDULER: "H H(1-2) 25 * *" }
  - { CMD: "$PYINT -u setup.py unittests -e \".*MODULE.*cuda.*\"", NAME: "UT_MODULE_CUDA", SCHEDULER: "H H(1-2) 25 * *" }
  - { CMD: "$PYINT -u setup.py unittests -e \".*MODULE.*\" -g \".*cuda.*\"", NAME: "UT_MODULE", SCHEDULER: "H H(1-2) 25 * *" }
  - { CMD: "$PYINT -u setup.py unittests -e \".*210.*\"", NAME: "UT_210", SCHEDULER: "H H(1-2) 25 * *" }
  - { CMD: "$PYINT -u setup.py unittests -e \".*300.*\"", NAME: "UT_300", SCHEDULER: "H H(1-2) 25 * *" }
  - { CMD: "$PYINT -u setup.py unittests -e \".*400.*\"", NAME: "UT_400", SCHEDULER: "H H(1-2) 25 * *" }
  - { CMD: "$PYINT -u setup.py unittests -e \".*(test_torch).*\"", NAME: "UT_TORCH", SCHEDULER: "H H(1-2) 25 * *" }
  - { CMD: "$PYINT -u setup.py unittests_LONG", NAME: "UT_LONG", SCHEDULER: "H H(1-2) 25 * *" }

after_script:
  - $PYINT -u setup.py bdist_wheel
  - if [ ${VERSION} == "3.9" and ${NAME} == "UT" ] then cp dist/*.whl {{root_path}}/../local_pypi/local_pypi_server fi

documentation:
  - if [ ${NAME} == "UT" ] then $PYINT -u setup.py build_sphinx fi
  - if [ ${NAME} == "UT" ] then cp -R -f _doc/sphinxdoc/build/html dist/html fi
